export const lang = {
  eng: {
    home: "Home",
    prices: "Prices",
    contactSales: "Contact Sales",
    trackShipment: "Track Shipment",
    signIn: "SignIn",
    trackingNo: "Tracking No.",
    lang: "العربيه",
    homeTxt1: "Join A New Generation Of Logistics!",
    homeTxt2: "Redefining how you ship, track, collect, deliver all through innovative tech-solutions and efficient operations.",
    "Cairo Sorting Facility": "Cairo Sorting Facility",
    "Haram Hub":"Haram Hub",
    "FM & Reverse Hub": "FM & Reverse Hub",
    "ticket created": "ticket created",
    "package received": "package received",
    "in transit": "in transit",
    "out for delivery": "out for delivery",
    "waiting for customer action": "waiting for customer action",
    "not yet shipped":"not yet shipped",
    "delivered to sender":"delivered to sender",
    "Shipment Details": "Shipment Details",
    "Details": "Details",
    "Time": "Time",
    "Date": "Date",
    "Hub": "Hub",
    "cancelled": "canceled",
    "delivered": "delivered",
    "Tanta Hub": "Tanta Hub",
    "Shipment Address": "Shipment Address",
    "Contact support": "Is there a problem with your shipment ?",
    "Retry delivery - the customer is not in the address.": "Retry delivery - the customer is not in the address.",
    "Postponed - the customer requested postponement for another day.": "Postponed - the customer requested postponement for another day.",
    "Customer is not answering.": "Customer is not answering.",
    "تأجيل - العميل طلب التاجيل ليوم اخر": "Postponed - the customer requested postponement for another day."



  },
  arb: {
    home: "الرئسيه",
    prices: "الاسعار",
    contactSales: "كلم المبيعات",
    trackShipment: "تتبع شحنتك",
    signIn: "تسجيل الدخول",
    trackingNo: "رقم التتبع",
    lang: "ENG",
    homeTxt1: "انضم إلى جيل جديد من الخدمات اللوجستية!",
    homeTxt2: "مفهوم جديد للشحن والتتبع والتجميع والتوصيل، كل ذلك من خلال حلول تقنية مبتكرة وعمليات فعالة.",
    "Cairo Sorting Facility": "منشأة الفرز بالقاهرة",
    "Haram Hub":"فرع الهرم",
    "FM & Reverse Hub": "فرع افم",
    "ticket created": "تم إنشاء الشحنة",
    "package received": "تم استلام الشحنة",
    "in transit": "في مرحلة انتقالية",
    "out for delivery": "خارج للتوصيل",
    "waiting for customer action": "في انتظار إجراء العميل",
    "not yet shipped":"لم يتم شحنه بعد",
    "delivered to sender":"سلمت إلى العميل",
    "Shipment Details": "تفاصيل الشحنة",
    "Details": "تفاصيل",
    "Time": "وقت",
    "Date": "تاريخ",
    "Hub": "فرع",
    "cancelled": "تم إلغاء الشحنه" ,
    "delivered": "تم التوصيل",
    "Tanta Hub": "فرع طنطا",
    "Shipment Address": "عنوان التسليم",
    "Contact support": "هل يوجد اي مشكله في شحنتك ؟",
    "Retry delivery - the customer is not in the address.": "أعد محاولة التسليم - العميل ليس في العنوان.",
    "Postponed - the customer requested postponement for another day.": "التأجيل - طلب العميل التأجيل ليوم آخر.",
    "Customer is not answering.": "العميل لا يجيب",
    "تأجيل - العميل طلب التاجيل ليوم اخر":"تأجيل - العميل طلب التاجيل ليوم اخر"
  },
};
